name: Run Linters
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true

    - name: Setup gems
      run: |
        cp test/support/gemfile.rb Gemfile
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: |
        bundle exec rubocop -S

    - name: Run Brakeman
      run: |
        bundle exec brakeman -5

    - run: yarn install

    - name: Run Stylelint
      run: node_modules/.bin/stylelint assets/stylesheets/

    - name: Run ESLint
      run: node_modules/.bin/eslint assets/javascripts/

    - name: Run MarkdownLint
      run: node_modules/.bin/markdownlint README.md CHANGELOG.md
